services:
  mysql:
    image: mysql:8.0
    container_name: ${DATABASE_CONTAINER_NAME}
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
